# Generated by Django 3.2.4 on 2021-07-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(1, 'Montag'), (2, 'Dienstag'), (3, 'Mittwoch'), (4, 'Donnerstag'), (5, 'Freitag'), (6, 'Samstag'), (7, 'Sonntag')], default=1, max_length=1)),
                ('open_from', models.TimeField()),
                ('close_at', models.TimeField()),
                ('special', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Öffnungszeit',
                'verbose_name_plural': 'Öffnungszeiten',
            },
        ),
    ]
