# Generated by Django 3.2.4 on 2021-07-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_alter_openinghours_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='day',
            field=models.CharField(choices=[('SP', 'Special'), ('MO', 'Montag'), ('DI', 'Dienstag'), ('MI', 'Mittwoch'), ('DO', 'Donnerstag'), ('FR', 'Freitag'), ('SA', 'Samstag'), ('SO', 'Sonntag')], default='SP', max_length=2, unique=True),
        ),
    ]
