# Generated by Django 3.1.4 on 2021-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=250)),
                ('setter', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('length', models.IntegerField()),
                ('route_num', models.CharField(max_length=4)),
                ('categorie', models.IntegerField(choices=[(0, 'Galerie Vorstieg'), (1, 'Galerie Toprope'), (2, 'Hauptwand Vorstieg'), (3, 'Turm Toprope'), (4, 'Turm Vorstieg')])),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routen',
            },
        ),
    ]
