# Generated by Django 3.2.4 on 2021-07-08 08:00

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yds', models.CharField(blank=True, max_length=10, null=True, verbose_name='YDS (USA)')),
                ('british_tech', models.CharField(blank=True, max_length=10, null=True, verbose_name='British (UK) Tech')),
                ('british_adj', models.CharField(blank=True, max_length=10, null=True, verbose_name='British (UK) Adj')),
                ('french', models.CharField(blank=True, max_length=10, null=True, verbose_name='Französisch')),
                ('uiaa', models.CharField(blank=True, max_length=10, null=True, verbose_name='UIAA (MiddleEurope)')),
                ('australia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Australia')),
                ('saxon', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sächisch (Sachsen/Nordböhmen)')),
                ('scandinavia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Scandinavia')),
                ('brasil', models.CharField(blank=True, max_length=10, null=True, verbose_name='Brasil')),
                ('fontainebleu', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fontainebleu')),
            ],
            options={
                'verbose_name': 'Grad Skala',
                'verbose_name_plural': 'Grad Skalas',
            },
        ),
        migrations.CreateModel(
            name='GradeScaleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Grad Skala Kategorie',
                'verbose_name_plural': 'Grad Skala Kategorien',
            },
        ),
        migrations.CreateModel(
            name='RouteSetterNickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Route Setter Nickname',
                'verbose_name_plural': 'Route Setter Nicknames',
            },
        ),
        migrations.CreateModel(
            name='RouteSetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('since', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nickname', models.ManyToManyField(to='routes.RouteSetterNickname')),
            ],
            options={
                'verbose_name': 'Route Setter',
                'verbose_name_plural': 'Route Setters',
            },
        ),
        migrations.CreateModel(
            name='RouteArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('name', models.CharField(max_length=250)),
                ('setter', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('length', models.IntegerField()),
                ('route_num', models.CharField(max_length=4)),
                ('archived', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.category')),
                ('grd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.gradescale', verbose_name='Grade')),
            ],
            options={
                'verbose_name': '[Archiv] Route',
                'verbose_name_plural': '[Archiv] Routen',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('a76fc873-42b1-4682-ae11-4fcc01565f20'), editable=False, null=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('name', models.CharField(max_length=250)),
                ('setter', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('length', models.IntegerField()),
                ('route_num', models.CharField(max_length=4)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.category')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.gradescale', verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routen',
            },
        ),
    ]
