# Generated by Django 3.2.4 on 2021-06-11 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3ecb1d56-b604-46ae-8765-620ffb73c70c'), editable=False, null=True),
        ),
    ]
