# Generated by Django 3.2 on 2021-05-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='routearchive',
            name='grade',
        ),
    ]
