# Generated by Django 3.2.4 on 2021-07-08 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bb06f8fb-214c-4c4c-a72e-9f360b269855'), editable=False, null=True),
        ),
    ]
