# Generated by Django 3.2.4 on 2021-06-11 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20210611_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a315ee30-80db-41a3-ac6a-b82061a4e4f0'), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='routearchive',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
