# Generated by Django 3.2.4 on 2021-07-08 08:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_route_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9fe73aae-c3cd-4695-8aa2-f573d07e47e6'), editable=False, null=True),
        ),
    ]
