# Generated by Django 3.2 on 2021-04-30 07:18

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_route_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=3)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('setter', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('length', models.IntegerField()),
                ('route_num', models.CharField(max_length=4)),
                ('categorie', models.IntegerField(choices=[(0, 'Galerie Vorstieg'), (1, 'Turm Toprope'), (2, 'Turm Vorstieg'), (3, 'Hauptwand'), (4, 'Galerie Toprope')])),
                ('archived', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '[Archiv] Route',
                'verbose_name_plural': '[Archiv] Routen',
            },
        ),
        migrations.RemoveField(
            model_name='route',
            name='active',
        ),
    ]
