# Generated by Django 3.2.4 on 2021-08-17 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_route_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('487c4b68-a062-4586-9e30-e7e20faa60f7'), editable=False, null=True),
        ),
    ]
