# Generated by Django 4.2.4 on 2023-08-31 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_alter_route_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('96c322ce-c958-48f3-ae0e-065dcfd9f9b3'), editable=False, null=True),
        ),
    ]
