# Generated by Django 3.2 on 2021-06-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_alter_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='grd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.gradescale', verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='routearchive',
            name='grd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.gradescale', verbose_name='Grade'),
        ),
    ]
