# Generated by Django 3.2 on 2021-04-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20210430_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routearchive',
            name='archived',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
