# Generated by Django 4.2.4 on 2023-08-31 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_alter_route_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescale',
            name='uuid',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dcfc8823-8ec1-4055-a034-e5fbf893c944'), editable=False, null=True),
        ),
    ]
