# Generated by Django 3.2.4 on 2021-07-03 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_alter_route_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSetterNickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Route Setter Nickname',
                'verbose_name_plural': 'Route Setter Nicknames',
            },
        ),
        migrations.RenameField(
            model_name='route',
            old_name='grd',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='french',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Französisch'),
        ),
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('39f6b0eb-d566-49ae-a600-1b25858b3631'), editable=False, null=True),
        ),
        migrations.CreateModel(
            name='RouteSetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('since', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nickname', models.ManyToManyField(to='routes.RouteSetterNickname')),
            ],
            options={
                'verbose_name': 'Route Setter',
                'verbose_name_plural': 'Route Setters',
            },
        ),
    ]
