# Generated by Django 3.2 on 2021-06-03 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_gradescalecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='routearchive',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
