# Generated by Django 4.2.4 on 2023-09-01 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_gradescale_uuid_alter_route_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dfe5eda0-0d36-448e-899c-c0a9815d6c5b'), editable=False, null=True),
        ),
    ]
