# Generated by Django 4.2.4 on 2023-09-04 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_alter_route_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('79fe22f0-150c-4ce2-a2d5-3808b3470aa1'), editable=False, null=True),
        ),
    ]
