# Generated by Django 4.2.4 on 2023-09-04 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_alter_route_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5e033204-36f1-49ad-a1f8-ff22c0ed8b78'), editable=False, null=True),
        ),
    ]
