# Generated by Django 4.2.5 on 2023-09-20 13:04

import colorfield.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_alter_route_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e8100166-5f13-4119-bc6e-a79b18e6763e'), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='routearchive',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
