# Generated by Django 3.2.4 on 2021-07-08 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0002_alter_route_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('private', models.BooleanField(default=False)),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('d', 'Divers'), ('o', 'Other')], default='o', max_length=1)),
                ('language', models.CharField(blank=True, choices=[('abk', 'Abkhazian'), ('aar', 'Afar'), ('afr', 'Afrikaans'), ('aka', 'Akan'), ('alb', 'Albanian'), ('amh', 'Amharic'), ('ara', 'Arabic'), ('arg', 'Aragonese'), ('arm', 'Armenian'), ('asm', 'Assamese'), ('ava', 'Avaric'), ('ave', 'Avestan'), ('aym', 'Aymara'), ('aze', 'Azerbaijani'), ('bam', 'Bambara'), ('bak', 'Bashkir'), ('baq', 'Basque'), ('bel', 'Belarusian'), ('ben', 'Bengali'), ('bih', 'Bihari languages'), ('bis', 'Bislama'), ('bos', 'Bosnian'), ('bre', 'Breton'), ('bul', 'Bulgarian'), ('bur', 'Burmese'), ('cat', 'Catalan, Valencian'), ('cha', 'Chamorro'), ('che', 'Chechen'), ('nya', 'Chichewa, Chewa, Nyanja'), ('chi', 'Chinese'), ('chv', 'Chuvash'), ('cor', 'Cornish'), ('cos', 'Corsican'), ('cre', 'Cree'), ('hrv', 'Croatian'), ('cze', 'Czech'), ('dan', 'Danish'), ('div', 'Divehi, Dhivehi, Maldivian'), ('dut', 'Dutch,\xa0Flemish'), ('dzo', 'Dzongkha'), ('eng', 'English'), ('epo', 'Esperanto'), ('est', 'Estonian'), ('ewe', 'Ewe'), ('fao', 'Faroese'), ('fij', 'Fijian'), ('fin', 'Finnish'), ('fre', 'French'), ('ful', 'Fulah'), ('glg', 'Galician'), ('geo', 'Georgian'), ('ger', 'German'), ('gre', 'Greek, Modern (1453–)'), ('grn', 'Guarani'), ('guj', 'Gujarati'), ('hat', 'Haitian, Haitian Creole'), ('hau', 'Hausa'), ('heb', 'Hebrew'), ('her', 'Herero'), ('hin', 'Hindi'), ('hmo', 'Hiri Motu'), ('hun', 'Hungarian'), ('ina', 'Interlingua\xa0(International Auxiliary Language Association)'), ('ind', 'Indonesian'), ('ile', 'Interlingue, Occidental'), ('gle', 'Irish'), ('ibo', 'Igbo'), ('ipk', 'Inupiaq'), ('ido', 'Ido'), ('ice', 'Icelandic'), ('ita', 'Italian'), ('iku', 'Inuktitut'), ('jpn', 'Japanese'), ('jav', 'Javanese'), ('kal', 'Kalaallisut, Greenlandic'), ('kan', 'Kannada'), ('kau', 'Kanuri'), ('kas', 'Kashmiri'), ('kaz', 'Kazakh'), ('khm', 'Central Khmer'), ('kik', 'Kikuyu, Gikuyu'), ('kin', 'Kinyarwanda'), ('kir', 'Kirghiz, Kyrgyz'), ('kom', 'Komi'), ('kon', 'Kongo'), ('kor', 'Korean'), ('kur', 'Kurdish'), ('kua', 'Kuanyama, Kwanyama'), ('lat', 'Latin'), ('ltz', 'Luxembourgish, Letzeburgesch'), ('lug', 'Ganda'), ('lim', 'Limburgan, Limburger, Limburgish'), ('lin', 'Lingala'), ('lao', 'Lao'), ('lit', 'Lithuanian'), ('lub', 'Luba-Katanga'), ('lav', 'Latvian'), ('glv', 'Manx'), ('mac', 'Macedonian'), ('mlg', 'Malagasy'), ('may', 'Malay'), ('mal', 'Malayalam'), ('mlt', 'Maltese'), ('mao', 'Maori'), ('mar', 'Marathi'), ('mah', 'Marshallese'), ('mon', 'Mongolian'), ('nau', 'Nauru'), ('nav', 'Navajo, Navaho'), ('nde', 'North Ndebele'), ('nep', 'Nepali'), ('ndo', 'Ndonga'), ('nob', 'Norwegian Bokmål'), ('nno', 'Norwegian Nynorsk'), ('nor', 'Norwegian'), ('iii', 'Sichuan Yi, Nuosu'), ('nbl', 'South Ndebele'), ('oci', 'Occitan'), ('oji', 'Ojibwa'), ('chu', 'Church\xa0Slavic, Old Slavonic, Church Slavonic, Old Bulgarian,\xa0Old\xa0Church\xa0Slavonic'), ('orm', 'Oromo'), ('ori', 'Oriya'), ('oss', 'Ossetian, Ossetic'), ('pan', 'Punjabi, Panjabi'), ('pli', 'Pali'), ('per', 'Persian'), ('pol', 'Polish'), ('pus', 'Pashto, Pushto'), ('por', 'Portuguese'), ('que', 'Quechua'), ('roh', 'Romansh'), ('run', 'Rundi'), ('rum', 'Romanian, Moldavian, Moldovan'), ('rus', 'Russian'), ('san', 'Sanskrit'), ('srd', 'Sardinian'), ('snd', 'Sindhi'), ('sme', 'Northern Sami'), ('smo', 'Samoan'), ('sag', 'Sango'), ('srp', 'Serbian'), ('gla', 'Gaelic, Scottish Gaelic'), ('sna', 'Shona'), ('sin', 'Sinhala, Sinhalese'), ('slo', 'Slovak'), ('slv', 'Slovenian'), ('som', 'Somali'), ('sot', 'Southern Sotho'), ('spa', 'Spanish, Castilian'), ('sun', 'Sundanese'), ('swa', 'Swahili'), ('ssw', 'Swati'), ('swe', 'Swedish'), ('tam', 'Tamil'), ('tel', 'Telugu'), ('tgk', 'Tajik'), ('tha', 'Thai'), ('tir', 'Tigrinya'), ('tib', 'Tibetan'), ('tuk', 'Turkmen'), ('tgl', 'Tagalog'), ('tsn', 'Tswana'), ('ton', 'Tonga\xa0(Tonga Islands)'), ('tur', 'Turkish'), ('tso', 'Tsonga'), ('tat', 'Tatar'), ('twi', 'Twi'), ('tah', 'Tahitian'), ('uig', 'Uighur, Uyghur'), ('ukr', 'Ukrainian'), ('urd', 'Urdu'), ('uzb', 'Uzbek'), ('ven', 'Venda'), ('vie', 'Vietnamese'), ('vol', 'Volapük'), ('wln', 'Walloon'), ('wel', 'Welsh'), ('wol', 'Wolof'), ('fry', 'Western Frisian'), ('xho', 'Xhosa'), ('yid', 'Yiddish'), ('yor', 'Yoruba'), ('zha', 'Zhuang, Chuang'), ('zul', 'Zulu')], default=None, max_length=3, null=True)),
                ('preferred_gradescale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.gradescale')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
