# Generated by Django 3.2 on 2021-06-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
