# Generated by Django 3.2.4 on 2021-06-20 20:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('info', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Modal Info',
                'verbose_name_plural': 'Modal info',
            },
        ),
    ]
