# Generated by Django 3.1.4 on 2020-12-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20201211_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visits',
            options={'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
        migrations.AddIndex(
            model_name='visits',
            index=models.Index(fields=['id'], name='counter_vis_id_8e4d13_idx'),
        ),
    ]
