# Generated by Django 3.1.4 on 2020-12-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_auto_20201221_1810'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visits',
            name='counter_vis_id_8e4d13_idx',
        ),
        migrations.AddIndex(
            model_name='visits',
            index=models.Index(fields=['id', 'added'], name='counter_vis_id_ac7029_idx'),
        ),
    ]
