# Generated by Django 3.2.4 on 2021-08-17 06:21

import colorfield.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrophyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('5bc31719-1f23-4c94-b270-e4fe5542724e'), editable=False, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
            options={
                'verbose_name': 'Trophy Kategorie',
                'verbose_name_plural': 'Trophy Kategorien',
            },
        ),
    ]
