# Generated by Django 3.2.4 on 2021-08-17 06:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_alter_route_uuid'),
        ('trophy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophycategory',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dbae3873-4310-426a-8177-16f1ef0aef40'), editable=False, null=True),
        ),
        migrations.CreateModel(
            name='TrophyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('2ef8f38e-add7-4302-b41a-6c63429437cd'), editable=False, null=True)),
                ('number', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trophy.trophycategory')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
            ],
            options={
                'verbose_name': 'Trophy Route',
                'verbose_name_plural': 'Trophy Routen',
            },
        ),
    ]
