# Generated by Django 3.2.4 on 2021-08-17 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0002_auto_20210817_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophyroute',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trophycategory',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('13a1e95a-f1a3-439f-a47f-0a99a67983c7'), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='trophyroute',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e8b6956e-cc5f-42be-9e28-3b85df1e0a1a'), editable=False, null=True),
        ),
    ]
