# Generated by Django 4.2.4 on 2023-08-31 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0003_auto_20210817_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophycategory',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('79c7d127-7755-4820-9a78-6880c336430e'), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='trophyroute',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='trophyroute',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8b112d5a-f5d0-4508-80fc-8ed67e213efd'), editable=False, null=True),
        ),
    ]
