# Generated by Django 4.2.4 on 2023-08-31 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0004_alter_trophycategory_uuid_alter_trophyroute_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophycategory',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e9f5fb32-58dd-48c1-9b76-694b3d9e8003'), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='trophyroute',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('19b988a1-3da4-4d22-a08a-e812ef21ba3b'), editable=False, null=True),
        ),
    ]
