# Generated by Django 4.2.5 on 2023-09-20 13:04

import colorfield.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0008_alter_trophycategory_uuid_alter_trophyroute_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophycategory',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='trophycategory',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f73b7917-1fec-43b3-be54-e24937101a1a'), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='trophyroute',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9e9002c5-fc87-4e85-a273-5586d4d4ca3d'), editable=False, null=True),
        ),
    ]
